[Fix/143] home UI & logic
Team-Hankki/hankki-android pull request #145
Opened 2024-08-03 01:07 UTC by chattymin

- closed #143 

## *⛳️ Work Description*
- 지도 회전시 나침반 나타나는 현상 제거
- StoreItem 위치 변경
- 네이버 로고 안보이게 숨기기
- 메인화면 default value 수정
- 불필요한 서버 통신 제거
- 상단 chip 클릭 오류 해결

## *📢 To Reviewers*
- 우하하~

2024-08-04 06:10 UTC, hyeeum requested changes
<img src="https://github.com/user-attachments/assets/08f4d791-e05a-44b7-84a3-69c8e3bce8b1" width=200 />

정렬칩 선택 후 x 버튼을 누르면 칩리스트 중 가장 왼쪽에 위치하는 버그가 발견되었사옵니다 


<img src="https://github.com/user-attachments/assets/c6de69b5-106c-46b8-ba95-4909af57ac1c" width=200 />

그리고 바텀 네비를 올린 후 칩을 선택하면 사진과 같이 중첩되는데 혹시 의도하신 걸까욥..?

추가적으로 이전 코드에서는 정렬칩이 Selected상태일때 칩이 아닌 다른화면을 클릭하면 칩 하위 리스트(ex-최신순/추천순/가격 낮은 순)가 사라졌던 것으로 기억하는데 지금은 고정이더라구요..! 혹시 이 부분도 의도하신걸까요??

2024-08-04 07:07 UTC, chattymin commented on feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
> +                            logoGravity = -1
이 부분에 대해서는 디자인과도 논의를 해봐야 할 것 같네요.
현재처럼 좌측 하단에 있게 된다면 UI가 변경되어야 할 것 같아요

2024-08-04 08:39 UTC, chattymin commented
> 정렬칩 선택 후 x 버튼을 누르면 선택한 옵션이 기존 종류 칩에 반영되는 버그가 발견되었사옵니다 ...!
어머 해결했습니다~~
 
> 그리고 바텀 네비를 올린 후 칩을 선택하면 사진과 같이 중첩되는데 혹시 의도하신 걸까욥..?
이 부분은 재현이 안되는데 한번 더 확인해주실 수 있나요??
정상적으로 동작하는 것 같습니다 :)
 
> 추가적으로 이전 코드에서는 정렬칩이 Selected상태일때 칩이 아닌 다른화면을 클릭하면 칩 하위 리스트(ex-최신순/추천순/가격 낮은 순)가 사라졌던 것으로 기억하는데(아니었다면 죄송하옵니다..) 지금은 고정이더라구요..! 혹시 이 부분도 의도하신걸까요??
맞습니다! 이부분은 의도한 부분이었어요~ 사용자 입장에서 메뉴를 내린 채 지도를 둘러볼 수 도 있다는 생각에 없앴습니다!

2024-08-04 08:40 UTC, chattymin commented on feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
> +                            logoGravity = -1
디자인과 협의한 결과 우측 상단으로 옮기기로 했어요~
클릭시 앱이 꺼지는 오류는 음... 열심히 수정해보겠스빈다 하하

2024-08-04 09:00 UTC, hyeeum commented
> 그리고 바텀 네비를 올린 후 칩을 선택하면 사진과 같이 중첩되는데 혹시 의도하신 걸까욥..?
>> 이 부분은 재현이 안되는데 한번 더 확인해주실 수 있나요??
정상적으로 동작하는 것 같습니다 :)

앗! 두번째 작동 순서를 잘못 말씀드렸네요
바텀 네비 올리고 칩 선택이 아니라 칩 클릭후 바텀네비를 올렸을 때 사진과 같이 중첩되게 나타났습니다..!


>> 맞습니다! 이부분은 의도한 부분이었어요~ 사용자 입장에서 메뉴를 내린 채 지도를 둘러볼 수 도 있다는 생각에 없앴습니다!

아마 요 부분과 연관이 있을 것 같네요! 의도하신 것이라면 민망민망

2024-08-04 09:49 UTC, hyeeum approved these changes
브랜치 최신화해서 해결된 것 확인했습니다:) 고생 많으셨어요오~!

2024-08-04 14:50 UTC, 0se0 approved these changes
혜음이가 열심히 해줘서 피드백 할 것이 없네요..👏 수고하셨습니다!

2024-08-04 14:50 UTC, 0se0 commented on feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
>                  HankkiTextSnackBar("스낵바")
ㅎㅎ... 😅

2024-08-04 14:50 UTC, 0se0 commented on feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
> +                _state.value.sortChipState
여기 칩 상태를 변경하고 데이터를 로드하는 로직이 여러 함수에서 반복되고 있는 거 같은데,
이를 chipState과 같은 함수로 추출하여 중복을 줄여보는 건 어떨까요?

2024-08-05 01:44 UTC, chattymin commented on feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
>                  HankkiTextSnackBar("스낵바")
이 부분은 추후 세영이가 수정할 예정이라 그냥 냅뒀어요 ㅋㅋㅋㅋㅋ
어차피 StateHoisting하여 Main에서 실행시켜야 해서 지워질 코드라 굳이 수정 안했습니다!

2024-08-05 02:04 UTC, chattymin commented on feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
> +                _state.value.sortChipState
오옹 똑또기네요
수정했습니다아~~~~

2024-08-05 02:04 UTC, merged

2024-08-05 02:08 UTC, chattymin commented on feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
> +                            logoGravity = -1
네이버 로고 클릭했을 때도 정상적으로 되도록 수정했습니다 :)
꼼꼼한 코리 최고~~~~!!!!!!

https://github.com/user-attachments/assets/c500a388-9fb2-4ad3-b1bb-7c17efa7b10b