[Fix #161] kakao sdk
Team-Hankki/hankki-android pull request #167
Opened 2024-08-09 10:13 UTC by 0se0

- closed #161

## *⛳️ Work Description*
- 카카오 로그인 웹, 앱

## *📸 Screenshot*
- 기존과 동일합니다.

## *📢 To Reviewers*
ㅎㅎ..
로그인 문제를 해결하려면 어쩔 수 없이 Context가 필요하더라구요.
근데 그냥 Context를 사용했을 때도 로그인이 잘 안되어서 에러를 찍어보니
<img src="https://github.com/user-attachments/assets/3e5e3799-593f-4077-a86b-a12f5e9e6c1c" width=800 />
위에 사진처럼 startActivity()를 호출할 때 Activity가 아닌 Context를 사용해서 나타는 문제라고 하여
기존에 사용했던 ApplicationContext는 애플리케이션의 전체 수명 동안 지속되기도 하고, 
특정 UI와 관련된 Activity의 생명 주기에 연결되지 않아 UI 관련한 작업 처리에 적합하지 않다고 판단하여Context를 Activity로 캐스팅하여 구현하였습니다.

2024-08-09 19:37 UTC, hyeeum approved these changes
아는 게 없어..달 내용이 없습니다..
저는 얼른 로그인 공부를 해야할 것 같네요...

2024-08-10 02:09 UTC, chattymin requested changes
고민 많이한 흔적이 보이는 코드였어요 ㅎㅎ 고생했습니다
제가 고잉때는 몰라서 이렇게 못했었는데 공부하다보니 이 방법이 더 좋은 것 같더라구용 ㅎ.ㅎ
요렇게 한번 바꿔봅시다!!!

2024-08-10 02:09 UTC, chattymin commented on feature/login/src/main/java/com/hankki/feature/login/LoginViewModel.kt
> +                    sendTokenToServer(token.accessToken)
이 함수를 쪼갠다고 생각하시면 될 것 같습니다!

43번째 줄을 Route에서 실행시키고, 성공 결과를 VIewModel로 보내준다면 그 값에 따라 KakaoTalkLogin에 해당하는 SideEffect를 방출시킬지, WebLogin에 해당하는 SideEffect를 방출시킬 지 결정하면 될 것 같습니다.

그 후 SideEffect를 Collect하는 Route에서 UserApiClient를 이용해서 로그인 로직을 실행시키고, token과 error를 viewModel로 보내 ViewModel에서 비즈니스 로직을 검증한 후 결과를 SideEffect로 방출하면 좋을 것 같아요

아래는 예시~
```
// Route
Route(){
   SideEffect콜랙트 함수{
        카카오로그인 -> startKakaoTalkLogin()
        웹 로그인 -> startKakaoWebLogin()
   }


    LoginScreen(
        onLoginClick = {
            viewModel.startKakaoLogin(UserApiClient.instance.isKakaoTalkLoginAvailable(this)
        }
    }
}


    private fun startKakaoTalkLogin() {
        UserApiClient.instance.loginWithKakaoTalk(this) { token, error ->
            viewModel.handleLoginResult(token, error)
        }
    }
    
    private fun startKakaoWebLogin() {
        UserApiClient.instance.loginWithKakaoAccount(this) { token, error ->
            viewModel.handleLoginResult(token, error)
        }
    }
   

// viewModel
fun startKakaoLogin(isKakaoTalkAvailable: Boolean) {
        viewModelScope.launch {
            if (isKakaoTalkAvailable) {
                sideEffect방출(카카오로그인)
            } else {
                sideEffect방출(웹로그인)
            }
        }
    }

 fun handleLoginResult(token: OAuthToken?, error: Throwable?) {
        if (error != null) {
            if (error is ClientError && error.reason == ClientErrorCause.Cancelled) {
                handleLoginError("로그인 취소")
            } else {
                sideEffect방출(웹로그인)
            }
        } else if (token != null) {
            sendTokenToServer(token.accessToken)
        }
    }
```

2024-08-11 13:11 UTC, chattymin approved these changes
굿굿~~
지금 코드도 문제없지만 이건 제 취향이라 한번 보고 좋다고 생각되면 반영해주세용

2024-08-11 13:11 UTC, chattymin commented on feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
> +}
이렇게 람다로 바꿔서 사용하는건 어떨까요??
매개변수로 viewModel을 넘기는 것보다 이렇게 람다로 하는게 결합도를 더 낮출 수 있습니다아
그리고 함수의 로그인 로직과 결과 처리를 분리할 수도 있지요

```suggestion
private fun startKakaoTalkLogin(
    context: Context,
    handleLogin: (OAuthToken?, Throwable?) -> Unit,
) {
    UserApiClient.instance.loginWithKakaoTalk(context) { token, error ->
        handleLogin(token, error)
    }
}
```

2024-08-11 13:22 UTC, 0se0 commented on feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
> +}
오..! 결합도까지 미처 생각을 못했네요😅
오늘도 열심히 배워갑니다.. ㅎㅎ
반영하였습니다! 감사합니다~

2024-08-11 13:23 UTC, merged