[Mod #178] Add condition to store launched effect
Team-Hankki/hankki-android pull request #184
Opened 2024-08-13 15:21 UTC by hyeeum

- closed #178

## *⛳️ Work Description*
- 페이지 내에서 하트 삭제 후 디테일 클릭 후 뒤로가기로 화면에 재진입했을 때 해당 식당의 하트가 회색으로 변경되고 그대로 남아있게 수

## *📸 Screenshot*

<img src="https://github.com/user-attachments/assets/2bb16a65-d37e-4291-bb42-b48d0b909a67" width=270 />

## *📢 To Reviewers*
- 현재 앱이 QA에 일치하긴하나 식당상세에서 반영한 좋아요값이 변경되지 않는 오류가 있어서 Ui최종 확인 후 다음 PR에서 고쳐보도록하겠습니다..!

2024-08-13 15:31 UTC, 0se0 approved these changes
수고하셨습니다!

2024-08-13 15:50 UTC, chattymin requested changes
수정하고 다시 리퀘스트 부탁드릴게요

2024-08-13 15:50 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
> +            if (myStoreState.uiState is EmptyUiState.Success) return@LaunchedEffect
이 부분을 서버에서 들어온 값과 기존의 값을 비교해서 샥샥 하면 좋을 것 같내요~

2024-08-16 07:38 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
이 PR과는 관계가 없지만, 96번줄에 있는 패딩을 해결하시면 문제가 해결될 것 같아요.
`myNavGraph`에서 모든 화면에서 paddingValue를 받아오고 있는데, 바텀네비가 있는 경우에만 받아오셔야 해요. 모든 뷰에서 받아오시면 안됩니다!

그래서 최종적으로 96번 줄을 `.statusBarsPadding()`으로 수정하시면 원하시는 화면이 나올거에요

Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/c0c6568d-f755-4334-a778-9b550de06547" width="300" > | <video src="https://github.com/user-attachments/assets/21271809-472f-44b4-8ef6-940294ea6b00" width="300" >

2024-08-17 09:35 UTC, hyeeum commented on feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
확인했습니다! 정말정말 감사합니다:)

2024-08-20 13:30 UTC, merged