[Fix/#193] 1차 QA 구현
Team-Hankki/hankki-android pull request #198
Opened 2024-08-17 15:11 UTC by hyeeum

- closed #193 

## *⛳️ Work Description*
 - 프로필 사진 디폴트로 변경
 - 나의 족보 → 나의 식당 족보 : 워딩 변경 -> 이부분은 혼동이 있어서 디쌤들께 다시 질문드렸어요! 확답받고 수정하겠습니다
 - 텍스트필드 타이핑중일때 두께 및 색상 변경
 - 좋아요 / 제보 둘다 : 하트 신버전으로 변경
 - 내 족보 디테일 : 하트 신버전으로 변경, 디바이더 길이 변경
 - 폴더모양 밑에가 좀 길다… 공유버튼과 폴더 아래 끝부분과 공간이 조금 긺
 - 내 족보 삭제시 : 삭제 → 삭제하기 워딩 변경
 - 로그아웃/회원탈퇴 : 돌아가기 → 유지하기 워딩 변경
 - 내 족보 추가 버튼 워딩 변경
 - 네비게이션 액션 제거
- 해시태그가 지워지지 않음
- null 처리 반영

## *📸 Screenshot*

이전 화면과 동일합니다 :)

## *📢 To Reviewers*
- 178번 PR해결하는 것만 남았네요 아자아자 (To.me)

2024-08-17 15:31 UTC, 0se0 approved these changes
수고하셨습니다.

2024-08-17 15:31 UTC, 0se0 commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiCountTextField.kt
> +                            )
오

2024-08-17 15:36 UTC, hyeeum commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiCountTextField.kt
> +                            )
이부분 잘못 짜서 다시 고치는 중...

2024-08-18 02:36 UTC, chattymin requested changes
구웃~ 
고생하셨서요!!

수정하고 다시 리퀘스트 바랍니다앙

2024-08-18 02:36 UTC, chattymin commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiCountTextField.kt
> +    }
요청해주신대로 const로 뺐습니다아! 적용해주시면 감사하겠서용

2024-08-18 02:36 UTC, chattymin commented on data/my/src/main/java/com/hankki/data/my/dto/response/UserInformationDto.kt
> +    val nickname: String
서버에서는 여전히 내려주고있을텐데 안받아도 괜찮나요?? 돌아가긴 할거같은데...

사용하지 않더라도 명세서 기반으로 하는건 어떻게 생각하시나용
아닌가 안쓰는거 받으면 추후에 보기에 불편하려나.... 어떻게 생각하세요

2024-08-18 02:36 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
> +                painterResource(id = R.drawable.ic_my_jogbo_fold)
contentScale을 제거한 이유가 있을까요?
기기대응을 위해서라면 있는게 좋을수도 있을 것 같아요

2024-08-18 02:36 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/StoreItem.kt
> +                    modifier = Modifier.width(16.dp),
저도 이번에 공부하다가 깨달았는데 Icon의 경우 [Material System Icon](https://m2.material.io/design/iconography/system-icons.html#grid-and-keyline-shapes) 규격인 24dp로 디폴트 값이 지정되어있습니다. 그렇기 때문에 규격을 변경시켜서 사용한다면 해당 컴포넌트의 존재 의의와 다른 것 같아요.
Image로 변경하시는건 어떨까요?

2024-08-18 02:36 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
> +            .statusBarsPadding()
이렇게 수정을 하셨다면 `MyStoreRoute`에서 받아온 paddingValue는 사용되고 있지 않는 것 같습니다. 그렇다면 불필요한 변수는 받아오지 않는 것으로 코드 수정부탁드릴게요

2024-08-18 02:36 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
> +            .statusBarsPadding()
그리고 해당 페이지 외에도 paddingValue를 받아오는 페이지들이 다수 보였는데 바텀네비를 쓰지 않는다면 그것들도 전부 수정 부탁드릴게요

2024-08-19 07:52 UTC, hyeeum commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
> +                painterResource(id = R.drawable.ic_my_jogbo_fold)
앗 이 부분 디자인 QA 반영하려고 이리저리 실험하다가 지워진 부분을 까먹고 커밋한 것 같네요 다시 수정해서 올리겠습니다!

2024-08-19 07:52 UTC, hyeeum commented on feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
> +            .statusBarsPadding()
수정하겠습니다 감사합니다~!

2024-08-19 07:54 UTC, hyeeum commented on feature/my/src/main/java/com/hankki/feature/my/component/StoreItem.kt
> +                    modifier = Modifier.width(16.dp),
컴포넌트 존재 의의와 다르다는 말에 동감합니다 바꾸도록 하겠습니다
코드 수정하고 관련된 부분 싹 갈아엎어야할 것 같네요..

2024-08-20 10:28 UTC, chattymin commented on data/my/src/main/java/com/hankki/data/my/dto/response/UserInformationDto.kt
> +    val nickname: String
아하 서버에서 수정되는군요!
그럼 이대로 갑시다아~

2024-08-20 10:30 UTC, chattymin approved these changes
확인하시고 머지해주세요~

2024-08-20 10:30 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
> +            .navigationBarsPadding()
엇... statusBar패딩과 navigationBar패딩을 쓰고있으면 바텀네비가 있다는 것 같은데 이런 경우는 Route에서 paddingValue받아와도 되지 않나용?

2024-08-20 10:30 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
> +            .navigationBarsPadding()
요기두! paddingValue를 받지 않고 이렇게 선언한 이유가 따로있을까용?

2024-08-20 12:05 UTC, hyeeum commented on feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
> +            .navigationBarsPadding()
이 화면의 경우 한끼 바텀네비를 사용하지는 않지만 바텀네비의 영역만큼 공백을 줘야하므로 사용했습니다..!
paddingValue를 통해 바텀영역을 가져오면 오른쪽 사진과 같이 한끼 바텀네비만큼의 영역이 잡혀서 따로 navigationBarsPadding을 사용했습니다

|전|후|paddingValue를 사용할 경우 바텀 영역|
|:---:|:---:|:---:|
|<img src="https://github.com/user-attachments/assets/958b0240-abca-4018-99dd-e6e455879645" width=270 />|<img src="https://github.com/user-attachments/assets/7811a5d9-5fa2-4532-ad3a-87a83d210b7f" width=270 />|<img src="https://github.com/user-attachments/assets/0230f999-db1d-4ead-ba16-30fa91fa346d" width=270 />|

2024-08-20 12:08 UTC, hyeeum commented on feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
> +            .navigationBarsPadding()
사실 요부분도 한끼 바텀네비를 사용하지않는 부분입니당.. navigationBarsPadding은 사실 있으나마나 이긴한데 혹시 제가 발견못한 부분이 있을까봐 넣어두긴했어요..!

2024-08-20 13:13 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
> +            .navigationBarsPadding()
아하 최고입니다!!

2024-08-20 13:13 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
> +            .navigationBarsPadding()
구웃!!!

2024-08-20 13:28 UTC, merged