[Feature #199] Update gradient
Team-Hankki/hankki-android pull request #200
Opened 2024-08-18 08:53 UTC by 0se0

- closed #199 

## *⛳️ Work Description*
- 이슈 참고

## *📸 Screenshot*
<img width="268" alt="image" src="https://github.com/user-attachments/assets/56197598-593b-4d9c-9193-82c9d2531f80">

## *📢 To Reviewers*
- 디자인에서 준 그라디언트 세로 길이가 154여서 그대로 주었습니다.

2024-08-19 06:45 UTC, hyeeum approved these changes
오 영광의 #200 축하드립니다 ㅎㅎ
수고많으셨어요~!

2024-08-19 09:24 UTC, chattymin requested changes
고생하셨습니다~~!
한번더 확인부탁드릴게요

2024-08-19 09:24 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +                    .padding(bottom = 154.dp),
오우 이렇게 큰 패딩값이 어쩌다 나오게 됐을까요...?
수정하면 좋겠서요

2024-08-19 09:24 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +                    val isLastItem = index == universities.size - 1
items 전부 해당 객체를 생성하게 된다면 리스트의 길이만큼 불필요한 객체가 생성될거에요
물론 변수를 선언해서 사용하는 것이 가독성에는 좋을 수 있지만, 해당 수식의 경우 길이도 짧고 메모리적 측면도 고려해봤을 때는 변수생성없이 바로 사용하는게 좋아요

2024-08-19 09:24 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +            )
같은 블러가 위아래로 존재하는 것 같아요.
그리고 PR시 올려주신 이미지를 보면 하단에는 블러가 적용이 안된 것 같은데 확인부탁드릴게요

2024-08-19 09:26 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +                    .padding(bottom = 154.dp),
아 블러의 크기에 맞춰서 높이를 준거였군요!
이 부분의 경우 제가 구현한 화면 중 `제보하기` - `식당검색` 화면에서 더욱 유동적인 방법으로 해결한 코드가 있습니다!
참고하시면 좋을 것 같아요~

2024-08-21 03:07 UTC, chattymin approved these changes
피그마랑 실행시켰을 때 한번 더 꼼꼼하게 확인 후 머지 부탁드려요

2024-08-21 03:07 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
>                      }
엇 기능명세가 이게 맞나요?
마지막이 아니라면 HorizontalDivider를 넣고, 마지막이라면 Spacer를 넣는거 아닌가요?

2024-08-22 06:04 UTC, 0se0 commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
>                      }
마지막 아이템에 7.dp가 들어가야 하고 마지막이 아니라면 HorizontalDivider와 7.dp가 들어가 14.dp 가 되는 로직입니다!

2024-08-22 06:27 UTC, merged