[Feature/#225]qa
Team-Hankki/hankki-android pull request #229
Opened 2024-08-27 13:18 UTC by 0se0

- closed #225 

## *⛳️ Work Description*
- 로딩뷰 추가 및 버튼 막기

## *📸 Screenshot*
https://github.com/user-attachments/assets/a4c0a46f-92d5-4be2-ae30-aaf28f708cba

## *📢 To Reviewers*
- 서버통신 플래그 문제인 줄 알았는데 레이아웃 문제일 줄이야..

2024-08-27 13:37 UTC, hyeeum approved these changes
진짜 레이아웃 문제였을 줄이야! 고생 많으셨습니다 :)

2024-08-27 13:37 UTC, hyeeum commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +                        .zIndex(1f)
요코드로 버튼 눌리는 문제를 해결하신 건가요!

2024-08-27 13:39 UTC, chattymin requested changes
고생하셨습니다! 수정하시고 다시 리퀘스트 부탁드릴게요

2024-08-27 13:39 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +        onPostSelectedUniversity = { universitySelectionViewModel.postUniversity() },
아마 :: 이거 적용 가능할듯!

2024-08-27 13:39 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionViewModel.kt
> +    }
혹시 이걸 안하면 이전 페이지에서 선택했던게 남아있나요?
그럼 이걸 안해도 네비게이션에서 restore를 없애면 될거에용

2024-08-27 13:39 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +                isLoading -> {
이렇게 로딩뷰가 아니라 저희 디자인에서 만들어준 로딩뷰를 적용해달라는 이야기였어요.
서버 통신 결과를 UiState로 받아서 그 상태에 맞춰 Loading 혹은 LazyColumn을 나타내게 해주세요

2024-08-27 13:43 UTC, 0se0 commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +                        .zIndex(1f)
헥 요 부분 제가 지우질 못했네요!
이 부분이 아니라 블러 부분에서 클릭 처리를 못하도록 막았습니다!!

2024-08-27 13:53 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +                        .clickable(enabled = false) {},
이 코드덕분에 터치가 안먹히는 거죠??
혹시 Main에 있는 네비게이션도 같은 현상이 있던데 거기에도 추가해주실 수 있을까요?

2024-08-27 15:05 UTC, chattymin approved these changes
고생하셨어요!!
메인 네비게이션에서 이동에 문제없다면 머지해도 부탁드려용

2024-08-27 15:05 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +                else -> {
혹쉬 이건 왜 넣으셨을까용??
uiState는 저희가 정한 state라서 else가 나올 수 없을 것 같아서 없어도 될 것 같아요오

2024-08-27 15:05 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +                UiState.Failure -> {}
요기에 제가 해둔것 처럼 Failure 화면을 만드는건 어떨까용??
물론 선택이라 없어도 되긴 합니다!

2024-08-27 16:49 UTC, chattymin requested changes
다시 수정부탁드릴게요

2024-08-27 16:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
> +    var isLoading by remember { mutableStateOf(false) }
이거 쓰지말고 UiState 쓰시면 됩니다.
그리고 쓰더라도 화면에 두면 안되고 State이용해서 ViewModel에 넣어야하구요

2024-08-27 16:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
> +    if (isLoading) {
UiState 사용해서 When문 쓰는걸로 바꿔주세요

그리고 화면 전체를 수정한다면 Screen이 아니라 Route에서 컨트롤 해야해요

2024-08-27 18:47 UTC, hyeeum commented on feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
> +                Spacer(modifier = Modifier.height(14.dp))
헉 매의눈 감사합니다!!

2024-08-28 03:37 UTC, chattymin approved these changes
마무리까지 고생하셨습니다~

2024-08-28 06:22 UTC, merged