[Feature/#20] university selection
Team-Hankki/hankki-android pull request #23
Opened 2024-07-05 01:55 UTC by 0se0

- closed #20 

## *⛳️ Work Description*
- 버튼을 컴포넌트로 만들기
- 대학 리스트만 스크롤 가능
- 각 대학교 선택 시 해당 대학 텍스트 색상 변경 및 버튼 활성화
- 다른 대학교 선택 시 이전 선택 텍스트를 색상을 디폴트로 변경하고 새로 선택된 대학 텍스트 색상 변경

## *📸 Screenshot*
https://github.com/Team-Hankki/hankki-android/assets/121383083/f9718c17-2052-4254-ae52-a3829a564530

## *📢 To Reviewers*
이번에도 리포트에서 university 버튼을 누르면 university화면으로 이동합니다.
현재는 하단 버튼 혹은 텍스트를 클릭 했을 때 모두 홈으로 이동할 수 있도록 구현했습니다!

2024-07-05 04:58 UTC, chattymin requested changes
컴포즈조차 익숙하지 않을텐데 디자인시스템도 만들고 이것저것 구현하시느라 고생하셨습니다 👍 
너무너무 잘하시네요!!

패키지 네임이 university라면 대학과 관련된 어떤 기능인지 헷갈리게 되고, 저희 도메인이 대학관련이다보니 추가 기능이 생겼을 때 네이밍이 모호해질 것 같습니다. 처음 생각하신 대로 `universityselection`으로 하는게 더 좋을것 같아요. 다만 카멜이 아니라 전부 소문자로 작성하면 될 것 같아요

2024-07-05 04:58 UTC, chattymin commented on core/designsystem/build.gradle.kts
> +    implementation(projects.core.common)
이건 제가 깜빡하고연결 못했었는데 감사합니다!!

그런데 혹시 프로젝트 연결을 최상단으로 옮겨줄 수 있을ㄹ까요??

```
// core
implementation(projects.core.common)

// other
implementation(libs.androidx.appcompat)
```

2024-07-05 04:58 UTC, chattymin commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/HankkiButton.kt
> +) {
매개변수를 넣을 경우 기본값이 없는것 먼저, 기본값이 있는 것 중에는 Modifier가 최상단에 오도록 해야합니다.

2024-07-05 04:58 UTC, chattymin commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/HankkiButton.kt
> +    }
1. `onClick`이 있는데 modifier의 `noRippleClickable`을 사용한 이유가 궁금합니다. 만약, 리플효과가 없는 클릭을 구현하고 싶었다면 Button이 아닌 Box와 같은 구성요소를 이용해서 버튼을 구현하는 것을 추천드립니다.
2. height에 고정dp를 사용하신 것 수정 부탁드립니다. 글자 크기가 커질 경우 글자가 잘릴 수 있습니다.
3. RoundedCornerShape를 import하면 shape가 조금 더 깔끔해지겠네요
4. Text에 style 적용  부탁드립니다.
5. 혹시 widthIn을 사용하신 이유가 있을까요?
6. 혹시 color 스타일 가이드에 alpha값이 적용된 컬러가 따로 표기되어있지 않나요?? 없다면 디자인에게 따로 명시적으로 빼달라고 요청해주세요

2024-07-05 04:58 UTC, chattymin commented on core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Color.kt
> +val Gray900 = Color(0xFF111111)
끝부분에 빨간색 - 모양이 생긴 것은 EOF이슈입니다. 
파일의 마지막에 한줄 엔터 넣어주세요

2024-07-05 04:58 UTC, chattymin commented on domain/dummy/src/main/java/com/hankki/domain/dummy/entity/response/UniversityModel.kt
> +)
dummy가 아닌 새로 university에 해당하는 domain을 만들어서 연결하시길 바랍니다

2024-07-05 04:58 UTC, chattymin commented on feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
> +    fun navigateToHome(navOptions: NavOptions? = null) {
option이 Nullable한 이유를 알 수 있을까요??

2024-07-05 04:58 UTC, chattymin commented on feature/report/src/main/java/com/hankki/feature/report/ReportRoute.kt
> +    ReportScreen(paddingValues, navigateToLogin = navigateToLogin, navigateToUniversity = navigateToUniversity)
옵션이 많아지면 가독성을 위해 개행 부탁드려요~

2024-07-05 04:58 UTC, chattymin commented on feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
> +fun NavGraphBuilder.reportNavGraph(paddingValues: PaddingValues, navigateToLogin: () -> Unit, navigateToUniversity: () -> Unit) {
여기도 개행~

2024-07-05 04:58 UTC, chattymin commented on feature/university/build.gradle.kts
> +}
여기도 implementation 순서 및 주석 작성해주세요

2024-07-05 04:58 UTC, chattymin commented on feature/university/src/main/java/com/hankki/feature/university/UniversityRoute.kt
> +    val selectedUniversity by universityViewModel.selectedUniversity.collectAsStateWithLifecycle()
최고!!!! 👍

2024-07-05 04:58 UTC, chattymin commented on feature/university/src/main/java/com/hankki/feature/university/UniversityRoute.kt
> +    val typography = hankkiTypography()
타이포그래피는 변수 생성하지 말고 바로 사용해주세요

2024-07-05 04:58 UTC, chattymin commented on feature/university/src/main/java/com/hankki/feature/university/UniversityRoute.kt
> +            style = typography.h1,
```suggestion
            style = HankkiTheme.typography.h1,
```

2024-07-05 04:58 UTC, chattymin commented on feature/university/src/main/java/com/hankki/feature/university/UniversityRoute.kt
> +            }
매번 Text마다 Divider를 넣어준다면 맨 밑에있는 텍스트에도 Divider가 있게 됩니다
Decorator를 활용해보면 좋을 것 같습니다.

2024-07-05 04:58 UTC, chattymin commented on feature/university/src/main/java/com/hankki/feature/university/UniversityViewModel.kt
> +    val selectedUniversity: StateFlow<String?> = _selectedUniversity
이 둘을 합쳐서 state로 나타낼 수 있지 않을까요??
지금의 방식은 mvvm에 더 가까운 것 같습니다.

2024-07-05 04:58 UTC, chattymin commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/HankkiButton.kt
> +    }
컴포넌트를 만들 때 디자인 시스템에서 기본적으로 셋팅되어있는게 있다면 해당 부분을 셋팅한 후 추가적으로 기능을 붙인다면 만들때 더욱 수월할거에요 :)

2024-07-05 05:03 UTC, hyeumm commented on core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Color.kt
> +val Gray900 = Color(0xFF111111)
알려주셔서 감사합니다! 앞으로 참고하겠습니다!

2024-07-05 05:07 UTC, hyeumm commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/HankkiButton.kt
> +) {
아하 매개변수를 이렇게 설정해야하는군요,저도 이부분 항상 헷갈렸는데 참고해서 수정하겠습니다

2024-07-05 06:19 UTC, 0se0 commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/HankkiButton.kt
> +    }
버튼을 컴포넌트로 뺄 때 높이가 고정된 것이라 생각하여 고정 높이를 사용하고 widthIn으로 최소너비를 보여주려고 구현 했다가 이것저것 만져보며 0dp로 해도 잘 보여진 다는 것을 깨닫고 지운다는 것을 깜빡하였습니다..ㅎ

고정 높이 부분은 패딩을 주는 것으로 수정하였는데 틀만 맞추고 스크린에서 따로 조정해주는 것이 더 좋은 방안일까요?
나머지 모두 수정했고 색상 요청 드렸습니다~!

2024-07-05 07:21 UTC, 0se0 commented on feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
> +    fun navigateToHome(navOptions: NavOptions? = null) {
현재 home으로 이동할 때,  `navigateToHome = { navigator.navigateToHome() }` 
이렇게 navOptions 호출 없이 구현을 해놔서
navigateToHome가 navOptions을 Nullable하게 설정하였습니다.

2024-07-05 07:40 UTC, 0se0 commented on feature/university/src/main/java/com/hankki/feature/university/UniversityRoute.kt
> +            style = typography.h1,
hankkiTypography()로 참조하는 방법은 초기화한 객체를 참조하는 것이 아니기 때문에 
앱 내에서 유동적으로 폰트가 변경될 시 반영되지 않습니다.
따라서 HankkiTheme.typography로 참조해야 합니다.

(제가 제대로 이해한 것이 맞을까요!)

2024-07-05 08:17 UTC, 0se0 commented on feature/university/src/main/java/com/hankki/feature/university/UniversityRoute.kt
> +            }
음..! 제가 Decorator를 제대로 못 찾아서 
[androidx.compose.foundation.lazy](https://developer.android.com/reference/kotlin/androidx/compose/foundation/lazy/package-summary)
이 문서를 보고 itemsIndexed를 활용하여 
`if (index < universities.size - 1) {
                HorizontalDivider(thickness = 1.dp, color = Gray200)
            }
`
이렇게 구현을 해보았습니다!

현재 반영된 코드는 알려주신 방법인 `Index마다 액션이 있는게 아니라 마지막인지만 필요한 상황
`인 것을 고려하여
`if (university != universities.last()) {
                    HorizontalDivider(thickness = 1.dp, color = Gray200)
              }` 이 방법으로 반영 해놓았습니다!

다만, 이 뷰는 대학 리스트가 계속 추가될 수 있는 부분으로 알고 있습니다!
그래서 items를 사용하게 되면 universities.last()를 반복적으로 호출하지만
itemsIndexed를 활용하면 그렇지 않아도 되니 더 좋을 수도 있다고 생각하는데,
이 부분에 대해 어떻게 생각하시는지 궁금합니다.

2024-07-05 08:30 UTC, 0se0 commented on feature/university/src/main/java/com/hankki/feature/university/UniversityViewModel.kt
> +    val selectedUniversity: StateFlow<String?> = _selectedUniversity
피드백 감사합니다!!
코드 리뷰 반영하여 리퀘스트 리뷰 드립니다.
궁금한 점 또한 코멘트 남겨놓았습니다! 확인해 주시면 감사하겠습니다~!!

2024-07-05 08:34 UTC, chattymin commented on feature/university/src/main/java/com/hankki/feature/university/UniversityRoute.kt
> +            style = typography.h1,
넵넵 맞습니다!! 물론 앱 내에서 유동적으로 변경될 일이 없긴 하지만...
hankkiTypography()의 경우 예시 파일을 참조하는 것이고, HankkiTheme은 객체를 참조하는 것이라고 생각하시면 됩니다.

2024-07-05 08:37 UTC, chattymin commented on feature/university/src/main/java/com/hankki/feature/university/UniversityRoute.kt
> +            }
index를 사용하더라도 items.size 라는 요소를 계속 호출하게 됩니다.
그렇기 때문에 호출로 인한 연산의 차이는 거의 없다고 봐도 됩니다.

또한 `if (index < universities.size - 1)`과 `if (university != universities.last())` 둘은 같은 기능을 하고있습니다. 하지만, 후자가 더 직관적이기 때문에 가독성적인 측면에서 좋다고 생각합니다

2024-07-05 08:53 UTC, hyeumm approved these changes
코드 작성/수정 속도가 엄청 빠르시네요 ㄷㄷ ... 저도 얼른 따라가겠습니다
코드와 코리를 보고 얼른 제 코드를 고쳐야겠단 생각이 드네요
이번에도 고생많으셨습니다!  :-)

2024-07-05 08:53 UTC, hyeumm commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/HankkiButton.kt
> +    textStyle: TextStyle = TextStyle.Default
폰트를 매개변수로 받아오는것이 재사용면에서 훨씬 좋겠네요!

2024-07-05 08:53 UTC, hyeumm commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +        UniversitySelectionModel(1, "한양대"), UniversitySelectionModel(2, "성신여대"),
데이터 넣느라 고생하셨어요 ㅜ.ㅜ

2024-07-05 08:53 UTC, hyeumm commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +                )
요 부분은 따로 컴포넌트로 빼는 건 어떨까요?? 
(주관적인 의견 -> 네이밍을 주고 직관적으로 리스트 아이템임을 표현하는 것도 괜찮지 않을까 생각합니다..!)

2024-07-05 08:57 UTC, chattymin approved these changes
정말 빠르게 반영해주시느라 고생하셨습니다!!
이번에 남긴 코리도 생각해보시고 반영한 후 머지하면 좋을 것같아요 :)

2024-07-05 08:57 UTC, chattymin commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/HankkiButton.kt
> +            .background(if (enabled) Red else Red.copy(alpha = 0.38f))
이 부분은 추후 디자인측에서 색상 속성을 준다면 수정하면 될거같아요~ 지금 완벽합니다!!

2024-07-05 08:57 UTC, chattymin commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/HankkiButton.kt
> +    textStyle: TextStyle = TextStyle.Default
혹시 textStyle이 버튼마다 다른가요??
다르다면 지금 너무좋지만, 같다면 Text에 넣어버려도 좋을 것 같아요 :)

2024-07-05 08:57 UTC, chattymin commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/HankkiButton.kt
> +        )
color를 따로 빼둔다면 더욱 직관적일 것 같아요
```suggestion
Text(
            text = text,
            style = textStyle
            color = White
        )
```

2024-07-05 08:57 UTC, chattymin commented on feature/universityselection/build.gradle.kts
> +    //domain
domain.dummy에 대한 종속성은 제거해주세요~

2024-07-05 08:57 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +import com.hankki.feature.university.R
이부분 패키지 네임이 제대로 안바뀐거 같아요. 한번 확인부탁드릴게요

2024-07-05 08:57 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +    UniversitySelectionScreen(
사이에 엔터 하나만 ㅎㅎㅎ...

2024-07-05 08:57 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +    universitySelectionState: UniversitySelectionState,
state내부에 있는 값들을 나눠서 넣어주는건 어떻게 생각하세요??
그렇게 되면 내부에서 State에 대한 종속성이 사라지고, 값들에 바로 접근이 가능해집니다.
universitySelectionState.universities -> universities   이렇게 바로 접근이 가능해져용

2024-07-05 08:58 UTC, chattymin commented on feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
> +    fun navigateToHome(navOptions: NavOptions? = null) {
이 부분에 대한 답변은 아래 comment를 하나 추가로 해서 답변하겠습니다.

2024-07-05 09:00 UTC, chattymin commented on feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
> +    }
이렇게 화면을 이동하게 되면 university에서 선택하기 버튼을 눌러 화면을 이동한 후 뒤로가기 버튼을 클릭 시 home에서 university로이동이 됩니다. navOption을 null로 했더라도 `navigateToHome = { navigator.navigateToHome() }`이부분에서는 Option을 넣어줘야할 것 같습니다.
이렇게 되면 앞으로 이동할 화면에서 모두 option을 넣어줘야 하지 않을까 라는 생각이 드네요

2024-07-05 09:03 UTC, chattymin commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +                )
오 그것도 좋은 것 같네요!!
여러곳에서 사용되지 않더라도 컴포넌트로 빼서 작성한다면 더욱 가독성이 좋아지니 이것도 좋은 방법인 것 같아요 

저도 신경 못쓰고 간 부분인데 꼼꼼한 코리 감사합니다!!

2024-07-05 12:48 UTC, 0se0 commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/HankkiButton.kt
> +    textStyle: TextStyle = TextStyle.Default
다릅니다~!

2024-07-05 12:51 UTC, 0se0 commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +                )
이 뷰에서만 사용되는 부분이라 컴포넌트로 빼야겠다는 생각은 못 했는데 좋은 의견 감사합니다!

2024-07-05 17:34 UTC, 0se0 commented on feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
> +    }
피드백 감사합니다! 모두 반영하였습니다!
그리고 아래는 제가 이해한 NavOptions의 동작인데 제대로 이해한 것이 맞을까요..!

현재 뷰의 스택은
report -> university selection -> home 이렇게 설정되어 있습니다.

NavOptions의 속성으로
`Popupto`를 하게 되면 스택이 report -> home 가 됩니다. 
(이때 `saveState = true`를 통해  university selection view의 상태를 저장합니다.)
그래서 대학교 선택 후 홈화면으로 돌아가 뒤로 가면 앱이 나가지게 됩니다.

`launchSingleTop = true `로 설정하여 현재 home이 백스택의 맨 위에 존재하기에 더 이상 home 인스턴스를 생성하지 않습니다. 
(만약 false라면  report -> home -> home 가능합니다.)

`saveState = true`였기에  `restoreState = true`를 통해 중간에 날려진 뷰들이 저장되어진 것을 불러올 수 있습니다. 그래서 홈화면으로 돌아왔을 때 하단바를 통해 리포트로 가면 대학교를 선택했던 화면이 나오게 됩니다. 이 화면에서 뒤로가기를 하게되면 기존의 리포트 화면이 나옵니다.

2024-07-05 18:25 UTC, chattymin commented on feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
> +    }
넵넵 맞는 설명입니다!! 열심히 공부하시느라 고생하셨어요!!
사실 해당 페이지는 뒤로가기로 입장하면 안되는 뷰라 `saveState`와 `restoreState`가 false여도 될 것 같긴 합니다
그리고 해당 페이지는 반드시 한번만 나와야 하니 `launchSingleTop`도 안해도 될거 같기도하고...
그냥 `Popupto`만 해도 될거같긴 하네요...!! 

근데 저도 네브옵션은 너무 어려운거 같아요 ㅠㅠ

2024-07-05 18:44 UTC, hyeumm commented on feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
> +            .navigationBarsPadding(),
navigationBar의 높이만큼 패딩을 추가한다

2024-07-07 02:33 UTC, 0se0 commented on feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
> +                        }
```suggestion
                    universitySelectionNavGraph(
                        navigateUpIfNotHome = { navigator.navigateUpIfNotHome() },
                        navigateToHome = {
                            val navOptions = navOptions {
                                popUpTo(navigator.navController.graph.findStartDestination().id) {
                                    saveState = true
                                }
                                launchSingleTop = true
                                restoreState = true
                            }
                            navigator.navigateToHome(navOptions)
                        }
                    )
```
이렇게 navigateUpIfNotHome을 추가하면 좋을 거 같다는 말씀 맞을까요?

2024-07-07 10:49 UTC, merged