[Feature/#18] my page view
Team-Hankki/hankki-android pull request #24
Opened 2024-07-05 19:53 UTC by hyeumm

- closed #18 

## *⛳️ Work Description*
- 피그마에 새로 추가된 폰트 SUIT H2 추가했습니다
- 마이페이지 뷰 제작했습니다

## *📸 Screenshot*

https://github.com/Team-Hankki/hankki-android/assets/118244028/903df813-a35a-499a-b4a2-8a4ab2d84553

## *📢 To Reviewers*
- xml만쓰다가 compose 사용하려니 아직 미숙한 부분이 많네요.. (세미나를 거쳤는데도..) 마음껏 비판해주세요(비난은 X)
- 화면 녹화할때는 피그마에 사용된 그래픽 사용했습니다. 서버에서 받아오는 이미지라서 녹화할때만 사용하고 삭제했으므로 실제 테스트에서는 다른 이미지 파일이 뜹니다!
- 기기상 네비게이션바로 인해 탈퇴하기 버튼이 보이지 않기 때문에 스크롤 기능을 추가했습니다.
- 네비게이션쪽 코드는 아직 건들지 않았(못했)습니다,그러므로 클릭 이벤트가 발생해도 화면 이동은 이루어지지않습니다 ㅜ.ㅜ

2024-07-05 20:11 UTC, chattymin requested changes
고생했습니다!!  너무 잘하는데요...???
코드가 정말 야무져서 기쁜맘으로 코리달았네요 ㅋㅋ
코드를 작성하는 한줄한줄에 이유를 가지고 작성한다면 더 좋은 코드가 될 것 같아요 :)

2024-07-05 20:11 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +    val myState = myViewModel.myState.collectAsStateWithLifecycle().value
by를 사용한다면 .value로 접근하지 않아도 돼요
```suggestion
    val myState by myViewModel.myState.collectAsStateWithLifecycle()
```

2024-07-05 20:11 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +    MyScreen(paddingValues, navigateToDummy = navigateToDummy, myState)
파라미터로 요구하는 네이밍과 넣는 값까지 전부다 입력해주세요~
그리고 이렇게 여러개가 들어갈 때에는 개행 부탁드립니다

2024-07-05 20:11 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +    myState: MyState
MyScreen이 MyState에 종속성을 가지지 않도록 State 자체를 넘기는 것이 아닌, MyScreen에서 필요로 하는 값들을 하나씩 넘기면 좋을 것 같아요.
추후 MyState가 수정되어도 MyScreen이 수정되는 일이 적어지도록요

2024-07-05 20:11 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +            )
내부 컴포넌트에 padding을 넣는것과 Spacer를 쓰는 것에는 어떤 차이가 있을까요??
어떤 기준으로 사용하는지 명확하면 좋을 것 같습니다.

그리고 내부 컴포넌트의 horizontal 방향으로 padding이 둘다 존재하기 때문에 Row에 padding을 주는 방법을 적용할 수 있을 것 같습니다. 내부 컴포넌트가 바뀌더라도 위치는 유지될 수 있다는 장점이 있어요

2024-07-05 20:11 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +            )
그리고 여기서는 Image를 썼는데 Coil의 AsyncImage를 안쓴 이유가 있을까요??

2024-07-05 20:11 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +        )
여기서도 top에 해당하는 16dp를 Spacer가 아닌 Padding으로 쓴 이유가 있을까요??
다른 부분에서는 Spacer를 사용하고 여기서는 Padding을 사용하고있는것 같네요

2024-07-05 20:11 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithArrowIcon.kt
> +            .noRippleClickable { onClick() },
이렇게 바꾸는건 어떨까요
```suggestion
 .noRippleClickable(onClick = onClick)
```

2024-07-05 20:11 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +        }
최고!!!! 👍

2024-07-05 20:11 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +    Column(
내부에 컴포넌트별로 중간중간 개행 추가하면 가독성이 더 좋아질 것 같아요~

2024-07-06 07:41 UTC, hyeumm commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +    myState: MyState
myState를 그대로 넘겨서 screen에서 세부데이터를 넣어주는 방법만 생각했었는데,말씀하신대로 하면 종속성이 사라져 추후 수정할때 편리할 것 같네요!
감사합니다 :)

2024-07-06 08:09 UTC, hyeumm commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +            )
> 그리고 여기서는 Image를 썼는데 Coil의 AsyncImage를 안쓴 이유가 있을까요??

서버 통신의 결과로 받아온 이미지를 불러올때 라이브러리를 사용했기에 자연스럽게 인터넷에서 이미지를 받아올 때만 사용하는 라이브러리라고 생각하여 로컬에서는 사용하는 것을 지양해야한다고 생각했던 것 같습니다..!

동일하게 coil을 사용하여 로컬 이미지를 로드하는 것이 더 좋은 방법일까요??

2024-07-06 08:13 UTC, hyeumm commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +            )
> 내부 컴포넌트에 padding을 넣는것과 Spacer를 쓰는 것에는 어떤 차이가 있을까요?? 어떤 기준으로 사용하는지 명확하면 좋을 것 같습니다.
> 
> 그리고 내부 컴포넌트의 horizontal 방향으로 padding이 둘다 존재하기 때문에 Row에 padding을 주는 방법을 적용할 수 있을 것 같습니다. 내부 컴포넌트가 바뀌더라도 위치는 유지될 수 있다는 장점이 있어요

제가 어려워했던 부분을 정확하게 짚어주시네요..
작성하면서 spacer와 padding을 어떻게 사용해야하는지 고민을 많이 했는데 이 부분과 관련된 부분들은 관련 내용을 조금만 더 찾아보고 다시 답변을 드리겠습니다..!

2024-07-06 11:27 UTC, 0se0 approved these changes
너무 잘하시네요!!! 수고 많으셨습니다~

2024-07-06 11:27 UTC, 0se0 commented on feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithImageAndBorder.kt
> +                shape = RoundedCornerShape(size = 12.dp)
`shape = RoundedCornerShape(12.dp)`
`shape = RoundedCornerShape(size = 12.dp)` 
하나로 통일하면 좋을 거 같아요!

2024-07-06 11:49 UTC, hyeumm commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +            .verticalScroll(scrollState),
넵! 하단 네비게이션바로 인해 탈퇴하기 버튼이 보이지 않는 문제를 해결하기 위해 해당 코드를 추가하였습니다..!

2024-07-06 11:49 UTC, hyeumm commented on feature/my/src/main/res/values/strings.xml
> +    <string name="sub_title">%1$s 님\n한끼 잘 챙겨 드세요</string>
디테일한 부분까지 짚어주셔서 감사합니다 :) !

2024-07-06 11:54 UTC, 0se0 commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +            .verticalScroll(scrollState),
아! 제가 디코에 올라온 클디 이슈를 방금 확인했네요!
추가적으로 box로 감싸 텍스트를 하단에 고정 시키는 방법도 있을 거 같아요!

2024-07-06 12:51 UTC, hyeumm commented on feature/my/src/main/res/drawable/ic_arrow_right.xml
헉 요 파일 정렬은 생각도 못했는데 알려주셔서 감사합니다 !!

2024-07-06 15:20 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +            )
> > > 내부 컴포넌트에 padding을 넣는것과 Spacer를 쓰는 것에는 어떤 차이가 있을까요?? 어떤 기준으로 사용하는지 명확하면 좋을 것 같습니다.
> > > 그리고 내부 컴포넌트의 horizontal 방향으로 padding이 둘다 존재하기 때문에 Row에 padding을 주는 방법을 적용할 수 있을 것 같습니다. 내부 컴포넌트가 바뀌더라도 위치는 유지될 수 있다는 장점이 있어요
> > 
> > 
> > 제가 어려워했던 부분을 정확하게 짚어주시네요.. 작성하면서 spacer와 padding을 어떻게 사용해야하는지 고민을 많이 했는데 이 부분과 관련된 부분들은 관련 내용을 조금만 더 찾아보고 다시 답변을 드리겠습니다..!
> 
> 내부 컴포넌트에 padding을 넣으면 컴포넌트의 크기가 확장됩니다. 예를 들어 텍스트를 버튼으로 사용할 경우,텍스트의 크기만큼 클릭 영역을 주면 작아서 터치 이벤트 감지가 잘 되지 않을 수 있기에, padding을 통해 터치 영역을 늘려줄 수 있습니다.
> 
> spacer의 경우 space라는 의미와 같이 빈 공간을 할당합니다. 예를 들어, 컴포넌트 간의 간격을 조정하는 경우 spacer를 사용할 수 있습니다.
> 
> 제가 생각하기에는 컴포넌트의 크기와 관련있는지 유무로 padding과 spacer 중 어느것을 사용할지 판단할 것 같습니다..!

너무 완벽한 답변입니다!! 세상 만족스럽네요 ㅎㅎㅎㅎ
컴포넌트 자체에 할당되어있는 공간이라면 Padding을, 그게 아니라 여백의 의미라면 Spacer를 쓰면 좋을것 같아요 :)

2024-07-06 15:20 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +            )
> > 그리고 여기서는 Image를 썼는데 Coil의 AsyncImage를 안쓴 이유가 있을까요??
> 
> 서버 통신의 결과로 받아온 이미지를 불러올때 라이브러리를 사용했기에 자연스럽게 인터넷에서 이미지를 받아올 때만 사용하는 라이브러리라고 생각하여 로컬에서는 사용하는 것을 지양해야한다고 생각했던 것 같습니다..!
> 
> 동일하게 coil을 사용하여 로컬 이미지를 로드하는 것이 더 좋은 방법일까요??

음 크게 문제는 없긴 하다만 coil자체가 coroutine을 지원하기 때문에 더욱 좋다고 알고있습니다.
그래서 이왕이면 coil로 통일하는건 어떨까요??

2024-07-06 15:21 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
> +        )
아하!! 사용자를 고려한 컴포넌트이군요!! 너무 좋습니다~~~~~~~

2024-07-06 15:25 UTC, chattymin approved these changes
진짜 너무 잘한다...
완벽합니다!!!!!!!!!!!! 채고!~!!@!@!~!~

2024-07-06 15:25 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithImageAndBorder.kt
> +        )
위에 코리에 단것 처럼 coil로 통일하는 것도 좋을 것 같아요~
근데 성능상이나, 이런 이점은 저도 잘 모르겠어요. 그저 하나의 컴포넌트를 사용한다면 모두가 알아보기 쉽다는 통일성적인 측면에서 말씀드리는 거라 혹여 성능적 문제가 있다거나 해당 상황에서는 Image가 쓰면 좋은 이유를 코멘트로 달아주시고 사용하셔도 됩니다!!
더 좋은 이유가 있으면 저도 배워야해서... ㅎㅎ 코멘트로 달아주세용

2024-07-06 15:59 UTC, hyeumm commented on feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithImageAndBorder.kt
> +        )
아하 통일성 측면에서 말씀해주신거였군요! 
일단 coil로 변경하고 성능적으로 달라지는 점이 발견된다면 추후에 공유하도록 하겠습니당!

2024-07-06 16:34 UTC, hyeumm commented on feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithImageAndBorder.kt
> +        )
coil AsyncImage로 수정하여 실행해보니 이미지를 불러오는 속도가 기존보다 느려져 Image를 그대로 사용하기로 했습니당!

2024-07-06 16:36 UTC, merged