Feature/#247 store detail edit
Team-Hankki/hankki-android pull request #264
Opened 2024-11-06 15:29 UTC by 0se0

## *📌 Issue*
- closed #247

## *⛳️ Work Description*
-2차 스프린트

## *📸 Screenshot*

### 동영상
- **Video 1:**  

https://github.com/user-attachments/assets/324beac3-1c6e-43e7-88df-4e6e8a800e32

---

### 이미지
| Image 1 | Image 2 |
|---------|---------|
| ![Image 2](https://github.com/user-attachments/assets/65cc3f05-7927-4c79-ac35-39b464e70ea8) | ![Image 3](https://github.com/user-attachments/assets/e33a9148-23e0-48b6-9134-6f86db7216d5) |

## *📢 To Reviewers*
- 메뉴 개수를 제대로 불러오지 못했습니다..

2024-11-06 17:59 UTC, chattymin requested changes
대부분의 뷰에서 같은 실수가 반복되고 있어요.
2/3정도만 읽고 밑에는 안읽어서 코리가 없는거지 수정할게 없는게 아니니까 전부 다 수정해서 다시 리퀘스트 부탁드려요.

2024-11-06 17:59 UTC, chattymin commented on data/storedetail/src/main/java/com/hankki/data/storedetail/repositoryImpl/StoreDetailRepositoryImpl.kt
> +    }
Timber 지워주세요~

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/navigation/StoreDetailScreen.kt
> +}
저희 이방식 사용하지 않아요.
기존에 사용하는 방식과 같은 방식으로 경로 설정해주세요.

2024-11-06 17:59 UTC, chattymin commented on feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
> +        navController.navigate("edit_mod_route/$storeId/$menuId/$menuName/$price", options)
아래 남겨뒀지만, 저희 기존에 사용하는 navigate와 다른 방식이에요.
기존에 사용하는 방식으로 작성해주세요.

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
> +    onEditMenuClick: (Long) -> Unit
선언 순서 지켜주세요

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
> +                else -> {}
else를 사용하신 이유가 있나요?

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
> +            menuList = listOf(MenuUiState()),
list가 아닌 persistantList사용해주세요

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
> +        Timber.d("StoreDetail menus: ${storeDetail.menus}")
여기도

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
> +            try {
try-catch는 비용이 큰 방법이에요
여기서 해당 방법을 사용한 이유를 잘 모르겠어요

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
> +    }
기존 리스트를 mutable로 바꾼 후 추가적인 수정을 하는 것은 너무 연산 비용이 큰 것 같습니다. 
다른 방법을 적용하면 좋을 것 같아요

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
> +            try {
여기서도 try-catch의 이유를 모르겠어요. 
그리고 만약 쓴다고 하더라도 Exception으로 처리하면 안됩니다. 원인을 알 수없어요

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/HankkiModTextField.kt
> +    onMenuFocused: (Boolean) -> Unit
선언 순서 지켜주시고, 컴포넌트를 만들때는 Modifier를 반드시 열어주세요

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/HankkiModTextField.kt
> +                        )
페인터는 리컴포지션의 대상이 돼요.
svg로 저장 후 imageVector로 사용해주세요

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/HankkiModTextField.kt
> +fun HankkiModPriceField(
위 컴포넌트에 적어둔 내용 여기도 반영 부탁드려요
그리고 price만 입력받는다면 숫자만 가능하도록 제한 걸어주세요

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/HankkiModTextField.kt
> +fun HankkiModPriceField(
그리고 윗 부분과 공통된 컴포넌트들이 있는데 묶어서 공통 컴포넌트로 활용해주세요

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/EditMenuBottomSheet.kt
> +    val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
이 기능을 true로 설정한 이유가 있나요?

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/EditMenuBottomSheet.kt
> +        onDismissRequest = { onDismissRequest() },
```suggestion
        onDismissRequest = onDismissRequest,
```

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/EditMenuBottomSheet.kt
> +            contentDescription = null,
어떤곳에선 contentDescription을 영어로 쓰고, 어떤곳은 한글, 어떤곳은 null이에요
이것에 대한 컨벤션을 맞춰봅시다. 추후에 다같이!

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/add/AddMenuRoute.kt
> +    menuList: List<MenuUiState>,
여기도 일반 List사용은 하지 말아 주세요

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/add/AddMenuRoute.kt
> +            )
이건 왜 있는 값인가요?

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/add/AddMenuRoute.kt
> +)
이 값이 Route 파일에 있는 이유가 없어요.
다른 곳으로 이동해주세요

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/add/AddMenuSuccessRoute.kt
> +        viewModel = viewModel,
screen으로 viewModel을 넘기면 안됩니다.
내부 값 혹은 함수만 넘기는걸로 수정해주세요

2024-11-06 17:59 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/add/AddMenuSuccessRoute.kt
> +        Spacer(modifier = Modifier.statusBarsPadding())
이렇게 선언하지 말고 column에 넣으면 됩니다
그리고 statusBarsPadding을 사용하신것 보다 Scaffold에서 주는 innerPadding을 사용하는 방법으로 바꿔주세요

2024-11-06 18:36 UTC, hyeeum approved these changes
일단 약간 졸린 상태로 본거라서... 내일 저녁에도 다시 한 번 확인하겠습니다
복학과 시험기간이슈로 너무 힘드셨을텐데 고생하셨어요 ㅜ.ㅜ 
나머지는 자잘한건데 8000원관련 이슈 + 뒤로가기 사라짐 이슈 한 번 확인부탁드려요 :)

2024-11-06 18:37 UTC, hyeeum commented on feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
> +    fun navigateToEditMod(storeId: Long, menuId: Long, menuName: String, price: String) {
아닌가 modify할 때 그 mod인가요?? 혼란

2024-11-07 11:05 UTC, 0se0 commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/EditModRoute.kt
> +            isPriceValid = newValue.text.toIntOrNull()?.let { it < 8000 } ?: false
요거 디샘들한테 물어보고 바꿀게용
<img width="458" alt="image" src="https://github.com/user-attachments/assets/31b82862-6d51-4991-9b44-67d9efe261ae">

2024-11-07 11:07 UTC, 0se0 commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/EditMenuRoute.kt
> +
여기 블러 추가 부분이라 추출하고 넣어 놓을게용

2024-11-07 13:04 UTC, 0se0 commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/EditModRoute.kt
> +            isPriceValid = newValue.text.toIntOrNull()?.let { it < 8000 } ?: false
이거 피그마 텍스트만 보고 잘 못 이해하고 있었네여..

2024-11-08 16:23 UTC, chattymin requested changes
고생하셨습니다!
한번 더 확인부탁드려요

2024-11-08 16:23 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/add/addmenu/AddMenuRoute.kt
> +                }
요 부분은 main에있는 errorSnackBar 끌고와서 연결하면 좋을 것 같네요!

2024-11-08 16:23 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/add/addmenu/AddMenuViewModel.kt
> +    private fun handleDeleteMenu(index: Int) {
함수 명에서 handle이 들어가야하는지 모르겠어요

2024-11-08 16:23 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/add/addmenu/AddMenuViewModel.kt
> +                emitSideEffect(AddMenuSideEffect.ShowError(error.message ?: "메뉴 추가 실패"))
나중에 snackBar 연결하면 조금 더 사용자 친화적인 텍스트로 수정해주세요~

2024-11-08 16:23 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/delete/DeleteSuccessRoute.kt
> +        onNavigateToStoreDetailRoute = { viewModel.navigateToStoreDetail() },
:: 사용으로 수정해주세욥

2024-11-08 16:23 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/delete/DeleteSuccessViewModel.kt
> +                }
추후에 할거라는걸 알긴 하지만, 현재 안한다면 지워주시고 그게 아니라면 errorSnackBar같은거라도 연결해주세용
그리고 Timber도 찍어주시고!

2024-11-08 16:23 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/editmenu/EditMenuRoute.kt
> +    }
key가 storeId인 이유가 있나요??

2024-11-08 16:23 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/editmenu/EditMenuRoute.kt
> +        }
이런거 분리해서 나타내면 더 가독성이 좋아질거같아요

2024-11-08 16:23 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/mod/ModRoute.kt
> +                    text = " 메뉴를",
어랏 앞에 스페이스바가

2024-11-08 16:23 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/mod/ModState.kt
> +    val priceFieldValue: TextFieldValue = TextFieldValue(),
String이 아니라 TextFieldValue를 사용하신 이유가 있나요?
TextFieldValue이 String보다 무겁고, State로 보기 힘들것같아요

2024-11-08 16:23 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/mod/ModSuccessRoute.kt
> +) {
Route에 있어야할 내용이 Screen에 있는 것 같아요

2024-11-08 16:23 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/mod/ModViewModel.kt
> +        this.menuId = menuId
이럴땐 네이밍을 다르게 하는것이 좋을것같아요

2024-11-08 16:23 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/navigation/navigateStoreDetail.kt
> +            onMenuSelected = { /*  */ },
이 주석은 왜 있나요?
기능이 빠진것같아요

2024-11-11 14:30 UTC, 0se0 commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/HankkiModTextField.kt
> +                            content?.invoke(this) ?: innerTextField()
아 제가 decorationBox를 사용해 컴포넌트화를 해서,
기본 텍스트 필드와 커스텀된 필드를 혼합하기 위해서 사용했습니다!

2024-11-11 14:33 UTC, 0se0 commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/SegmentedButton.kt
> +                    .background(Color(0x1A9B331C))
디샘들한테 건의드리도록 하겠습니당

2024-11-11 14:39 UTC, 0se0 commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/mod/ModRoute.kt
> +                    text = " 메뉴를",
헥 요거는 위에 텍스트에 있는 메뉴 이름 때문에 이렇게 했습니당.
ex) **된장찌개** 메뉴를

2024-11-12 11:19 UTC, 0se0 commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/editmenu/EditMenuRoute.kt
> +    }
메뉴 수정 후 다시 EditMenuRoute로 돌아올 때 최신 데이터를 보여주기 위해 key로 사용했습니다.

2024-11-12 12:38 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/editmenu/EditMenuRoute.kt
> +    }
제 생각으로는 Screen은 다시 돌아왔을 때에 다시 그려지기 때문에 Unit으로 해도 LaunchedEffect 내부 코드가 동작 될거같아요.
한번만 실험해봐주시고 Unit으로 해도 다시 동작된다면 Unit으로, 동작되지 않는다면... 죄송합니다 😿

2024-11-16 06:33 UTC, chattymin approved these changes
어우 깔끔하게 잘 하셧네용
이번 스프린트도 고생 많으셨습니다!!!

2024-11-16 06:33 UTC, chattymin commented on feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
> +            }
showDeleteButton이 false일 때 Box에 해당하는 영역은 존재할거같아요!
두가지 궁금증이 있어요

1. Box로 묶은 이유가 있나요? 단순 width라면 Column에서 처리해도 될 것 같아요! 그게 아니라면 Box도 같이 If문 안에 있는건 어떨까요?
3. Text에는 값이 없는데 들어간 이유가 있는걸까용?

2024-11-16 06:33 UTC, chattymin commented on feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
> +
진짜 궁금. 절대 뭐라하는거 아님 ㅋㅋㅋ

엔터 두줄을 넣는걸 선호해서 한줄 더 넣은건지??

2024-11-16 06:33 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/add/addmenu/AddMenuViewModel.kt
> +            AddMenuEvent.OnBackClick -> backClick()
찐 MVI를 도입하셨군요! 너무 좋습니다!

그런데 MVI라면 Event라는 단어보다는 Intent라는 단어가 더 일반적이긴 합니당 ㅎㅎㅎ
물론 Event라고 해도 전혀 문제 없어요~~~

2024-11-16 06:33 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/editmenu/EditMenuRoute.kt
> +                    //메세지
요것...두... 시간나면 해주세용

2024-11-16 06:33 UTC, chattymin commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/editmenu/EditMenuState.kt
> +        get() = menuItems.size
오옹 게터 사용 조하요

2024-11-16 11:15 UTC, 0se0 commented on feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
> +            }
1. 리스트가 하나 남아있을 상황에서는 delete 버튼을 없애자는 의견이 나와서 이렇게 구현하였습니다!
2. text부분 만큼의 크기를 주어서 delete 버튼의 위치를 조정한 것입니다!

2024-11-16 11:15 UTC, 0se0 commented on feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
> +
전혀.....

2024-11-16 11:30 UTC, 0se0 commented on feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/editmenu/EditMenuRoute.kt
> +    }
요거 unit으로도 잘 동작하네요!!!!!

2024-11-16 15:29 UTC, chattymin approved these changes
채고~~~~
완전 고생했수용 🎉

2024-11-17 07:03 UTC, merged