[Feature/#17] kakao login token
Team-Hankki/hankki-android pull request #35
Opened 2024-07-09 20:00 UTC by 0se0

- closed #17 

## *⛳️ Work Description*
- 서버에 accesstoken post
- 서버로부터 accessToken, refreshToken 받기
- datastore에 토큰 저장하고 clear
- 클린아키텍처 적용
- 상단 텍스트 및 버튼 적용

## *📸 Screenshot*
<img width="346" alt="image" src="https://github.com/Team-Hankki/hankki-android/assets/121383083/6298adc4-3a68-48d8-9591-f5aabc368051">

## *📢 To Reviewers*
- 클린 아키텍처를 적용해보려고 노력했는데, 이 부분 중점적으로 봐주시면 감사하겠습니당
- clearInfo()함수 동작시켜서 accessToken과 refreshToken 삭제 되는 것 확인했습니다.
- 추가로 로그인 뷰 중간 부분에 로티를 넣어야 해서 임시로 안드로이드 이미지를 넣어놓았습니다.

2024-07-09 20:38 UTC, chattymin requested changes
굿굿!! 고생하셨습니다!!
역시 기깔나는 코드네요~

2024-07-09 20:38 UTC, chattymin commented on core/datastore/src/main/java/com/hankki/core/datastore/di/SharedPreferenceModule.kt
> +        return context.getSharedPreferences("prefs", Context.MODE_PRIVATE)
"prefs"도 companion object 로 빼주세요~

2024-07-09 20:38 UTC, chattymin commented on core/datastore/src/main/java/com/hankki/core/datastore/di/SharedPreferenceModule.kt
> +        return context.getSharedPreferences("prefs", Context.MODE_PRIVATE)
한줄짜리는 =로 표시하는건 어떨까요???

2024-07-09 20:38 UTC, chattymin commented on data/login/build.gradle.kts
> +    implementation(projects.domain.login)
기존 양식 맞춰서 해주세요
```suggestion
    // domain
    implementation(projects.domain.login)
```

2024-07-09 20:38 UTC, chattymin commented on domain/login/src/main/java/com/hankki/domain/login/entity/request/LoginRequestModel.kt
> +)
<img width="665" alt="image" src="https://github.com/Team-Hankki/hankki-android/assets/52882799/d20d4c22-616d-4162-9839-e4ba8bf49dc7">
Model의 경우 현실세계의 객체를 의미합니다. 그렇기 때문에 domain에는 어울리지 않는 네이밍인 것 같네요.
domain에서 사용하는 용도인 entity를 사용하는건 어떨까요?

2024-07-09 20:38 UTC, chattymin commented on data/login/src/main/java/com/hankki/data/login/dto/response/LoginResponseDto.kt
> +    fun toLoginModel() =
Model->Entity로 바뀌게 된다면 이런 함수명도 바껴야 할 것 같습니다.

2024-07-09 20:38 UTC, chattymin commented on data/token/build.gradle.kts
> +    implementation(projects.core.datastore)
이 부분도 기존 방식 유지해주세요

2024-07-09 20:38 UTC, chattymin commented on feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
> +            .navigationBarsPadding()
혹시 statusBarPadding은 안빼도 괜찮은 뷰인가요?

2024-07-09 20:38 UTC, chattymin commented on feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
> +            Spacer(modifier = Modifier.height(107.dp))
큰 숫자를 고정 dp로 사용하는 것은 지양해주세요.
Alignment를 사용하거나, weight를 활용하는 것을 권장합니다.

2024-07-10 05:24 UTC, hyeumm approved these changes
로그인 구현하느라 고생 많으셨어요 : -) 
클린이 잘 적용되어 있어서 제가 딱히 달 코멘트가 없군요..
저도 얼른 피알 올리고싶네요

2024-07-10 05:24 UTC, hyeumm commented on feature/login/src/main/java/com/hankki/feature/login/navigation/LoginNavigation.kt
> +data object Login : Route
요부분 아래에 공백 하나 넣어주셔야할 것 같아유

2024-07-10 05:24 UTC, hyeumm commented on feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
> +            Spacer(modifier = Modifier.height(107.dp))
저도 하나 알아갑니다 감사합니다 :)

2024-07-10 05:24 UTC, hyeumm commented on feature/login/src/main/res/values/strings.xml
> +    <string name="done_worry">밥값 고민 끝,\n다함께 한끼족보를 만들어봐요</string>
done은 오타가 아닌거죠...?

2024-07-10 05:25 UTC, 0se0 commented on feature/login/src/main/res/values/strings.xml
> +    <string name="done_worry">밥값 고민 끝,\n다함께 한끼족보를 만들어봐요</string>
ㅋㅋㅋ네...

2024-07-10 06:45 UTC, chattymin commented on feature/login/src/main/res/values/strings.xml
> +    <string name="done_worry">밥값 고민 끝,\n다함께 한끼족보를 만들어봐요</string>
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-07-10 06:47 UTC, chattymin approved these changes
징챠 고생많이 했어요!!!
이제 토큰 재발급 interceptor까지 달려봅시다 🚀🚀

2024-07-10 06:47 UTC, chattymin commented on data/token/build.gradle.kts
> +    //domane
오타~

2024-07-10 06:47 UTC, chattymin commented on core/datastore/src/main/java/com/hankki/core/datastore/di/SharedPreferenceModule.kt
> +}
요기두 공백~

2024-07-10 06:52 UTC, merged