[Feature/#26] my jogbo
Team-Hankki/hankki-android pull request #38
Opened 2024-07-10 15:16 UTC by hyeumm

- closed #26

## *⛳️ Work Description*
- 편집모드일때 뒤로가기 버튼 클릭시,편집모드 해제
- 편집모드아닐때 뒤로가기 버튼 클릭시,뒤로가기
- 다이얼로그 보이기

## *📸 Screenshot*

https://github.com/Team-Hankki/hankki-android/assets/118244028/b1584b89-a7a4-4d44-9c67-d2a737047643

## *📢 To Reviewers*
- 이게 맞는지 헷갈리네요..
- 비판 많이 해주세요..이번 코드 자신없음 :-(

2024-07-10 16:08 UTC, chattymin requested changes
고생하셨습니다!!
StateHoisting을 이용해서 State를 구성하면 좋을 것 같아요 :)

2024-07-10 16:56 UTC, 0se0 approved these changes
수고하셨습니다~~!!👍👏

2024-07-10 16:56 UTC, 0se0 commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboItem.kt
> +                contentDescription = null
contentDescription 좀 더 자세히 적어주시면 좋을 거 같아요!

2024-07-10 16:56 UTC, 0se0 commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboItem.kt
> +                    .border(2.dp, Red, shape = RoundedCornerShape(12.dp))
매개변수 적어주시면 더 좋을 거 같아요!

2024-07-10 16:56 UTC, 0se0 commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboItem.kt
> +                    painter = painterResource(id = com.hankki.core.designsystem.R.drawable.ic_check_btn),
여기는 따로 import가 안되나요??
core dependencies를 추가하면 될 거 같은데,
한번 찾아보시고 저도 알려주시면 감사하겠습니다!ㅎㅎ

2024-07-10 16:56 UTC, 0se0 commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboItem.kt
> +                .clickable(onClick = editJogbo),
여기는 리플 효과가 있어야 하는 곳인가요?

2024-07-10 16:56 UTC, 0se0 commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboItem.kt
> +            }
@chattymin 감동적이네요.

2024-07-10 16:56 UTC, 0se0 commented on feature/my/src/main/java/com/hankki/feature/my/my/MyState.kt
> +package com.hankki.feature.my.my
패키지 이름을 좀 더 상세히 적어주시면 좋을 거 같아요!

2024-07-10 19:30 UTC, hyeumm commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboItem.kt
> +                .clickable(onClick = editJogbo),
디자이너 선생님과 상의한 결과 리플없이 통일하기로 결정했습니다 수정할게요 :--)

2024-07-14 15:49 UTC, chattymin requested changes
이번에만 수정하면 진짜 끝인듯!!!!!
한번만 더 화이팅 :)

2024-07-14 15:49 UTC, chattymin commented on feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
> +                        navigateToMyJogbo = { navigator.navigateToMyJogbo() }
리플렉션 적용 부탁드려용

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailRoute.kt
> +    val showShareDialog = remember { mutableStateOf(false) }
값을 viewModel에 넣어주세요. State로 관리하면 좋을 것 같습니다

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailRoute.kt
> +        )
이 부분은 구두로 설명해드리겠습니다.
초기 셋팅부터 viewModel과 연결해서 하면 좋을 것 같아요

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailRoute.kt
> +        )
그리고 추후 해야하는 작업의 경우 아래와 같이 설정하면 나중에 모아서 볼 수 있어요~
`// TODO: 해야할일`

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailRoute.kt
> +                val storeList = storeItems[index].stores
items내부에 list를 넣는다면 index가 아니라 item을 바로 받을 수 있어요

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailRoute.kt
> +                        eidtSelected = {},
비어있는 함수의 경우 위에 알려드린 주석을 통해 추가 작업해야함을 나타낸다면 코드리뷰할때도 좋을 것 같습니다. 실수로 비운건지, 실제로 기능이 없는건지 볼때 애매하네요.
만약 없어도 되는 함수라면 옵셔널로 빼면 좋을 것 같습니다

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailState.kt
> +        )
초기 state에 빈 값을 넣어 둔 이유가 있을까요? 없다면 비워주세요

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyStoreRoute.kt
다음 Route에서 PR에 올릴 예정이라고 구두로 들었습니다. 다음 PR에서 채워져있을 내용 기대할게요~ :)

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/AddJogboItem.kt
> +            .noRippleClickable(onClick = onClick),
```suggestion
modifier = modifier
    .wrapContentSize()
    .clip(RoundedCornerShape(12.dp))
    .background(if (isEditMode) RedLight else Red)
    .run {
        if (!isEditMode) noRippleClickable(onClick = onClick)
        else this
    }
```
이런 방법은 어떨까요?

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithImageAndBorder.kt
> +            .padding(top = 18.dp, bottom = 17.dp)
이런 값들 보니까 대부분 디자인 실수여서 vertical 18로 통일해도 될 것 같습니다

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/DialogWithButton.kt
> +    Dialog(onDismissRequest = { onDismissRequest() }) {
```suggestion
    Dialog(onDismissRequest = onDismissRequest) {
```
아마 이렇게도 될거에요

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/DialogWithButton.kt
> +    Dialog(onDismissRequest = { onDismissRequest() }) {
밑에있는 다른 함수들도 수정해주세요

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
> +            )
우아 개쩐다
전 사실 이런거 몰랐어요 ㅋㅋㅋ 하나 배워갑니당

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
> +            }
태그가 1개가 들어올 수도 있고, 2개가 들어올 수 있습니다.
list를 이용해서 종속적으로 작성해주세요

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboHashtagChip.kt
> +        text = "#$chiptext",
생성시 #을 포함한 채로 서버에 보내줄 예정입니다. 여기서는 빼도 될 것 같네요

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboItem.kt
> +            .noRippleClickable(onClick = editJogbo)
이 부분도 위에 알려드린 modifier 설정하는 법 사용하시면 될 것 같습니다.

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/StoreItem.kt
> +            }
item자체가 가지고 있어야 하는 정보가 아닌 것 같습니다.
가로선을 나타내는 용도라 생각되는데 해당 컴포넌트를 호출하는 곳에서 `HorizontalDivider`로 사용하시면 될 것 같습니다.

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
> +        resetJogboState = { myJogboViewMidel.resetJogboState() }
셋다 리플렉션 적용 가능합니다아

2024-07-14 15:49 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
> +                        Modifier.noRippleClickable(onClick = navigateToJogboDetail),
```suggestion
                    modifier = Modifier.noRippleClickable(onClick = if(editMode) {} else navigateToJogboDetail),
```
간단한 설정 하나의 경우에는 이렇게 해도 좋아용

2024-07-14 16:04 UTC, 0se0 approved these changes
수고하셨습니다~!!!

2024-07-14 16:23 UTC, chattymin approved these changes
이것두~~!!!

2024-07-14 16:23 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailRoute.kt
> +    storeItems: PersistentList<MyJogboDetailEntity>
이 값이 리스트가 아니어야 할 것 같습니다.

2024-07-14 16:23 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailRoute.kt
> +            chip2 = storeItems[0].tags[0],
```suggestion
            chips = tags
```
chips를 list로 바꾸고 이렇게 넘기면 어떨까요

2024-07-14 16:23 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailRoute.kt
> +            userImage = "", //image 함수 호출
얘들도 state에 넣어주시기 바랍니다.

2024-07-14 16:23 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailRoute.kt
> +            userImage = "", //image 함수 호출
state에 userNickname, userProfileImage와 같이 state를 넣어두고, 해당 값을 api 호출해서 받은 값으로 덮어쓰기 한다면 자동으로 변경되게 됩니다. 즉, Screen의 매개변수로 저 두값을 받는다면 viewModel에서의 값이 변경되었을 때 해당 state를 collect하고있으므로 리컴포지션 되게 됩니당!

2024-07-14 16:23 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailViewModel.kt
> +}
EOF ㅋㅋ

2024-07-14 16:23 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyStoreRoute.kt
> +
불필요한 공백도 지워주웅

2024-07-14 16:24 UTC, chattymin requested changes
하핫 실수로어프루브 했네용~ 수정하고 다시 알려주십셔

2024-07-14 18:44 UTC, hyeeum commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
> +                    )
몰라서...몰라서 못했어요...

2024-07-14 18:57 UTC, hyeeum commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailRoute.kt
> +            buttonTitle = "확인",
헉 이부분 누락되었네요 꼼꼼한 리뷰 감사함당

2024-07-14 19:02 UTC, hyeeum commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailViewModel.kt
> +}
프로그램 설치햇으니 이제 더이상 EOF로 코리 달릴 일은 없을것임니다 ㅋㅋ

2024-07-14 19:59 UTC, chattymin requested changes
찐찐찐막!!!!!!
가보자구용

2024-07-14 19:59 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailState.kt
> +    val showShareDialog: MutableState<Boolean> = mutableStateOf(false)
mutableState말고 단순한 Boolean으로 해주세요. MutableState쓰시면 안됩니다

2024-07-14 19:59 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailRoute.kt
> +            onConfirmation = { shareDialog.value = false }
state 변경을 ui에서 처리하면 안되고 viewModel에서 처리해주세요

2024-07-14 19:59 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyJogboDetailRoute.kt
> +                val storeList = storeItem.stores
여기서 변수를 선언하지 마시고 Route에서 Screen으로 값을 넘겨줄 때 list로 넘겨주세요

2024-07-14 19:59 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyStoreRoute.kt
> +    modifier: Modifier = Modifier,
옵셔널의 최상단으로 둬야합니다. 옵셔널이 아닌걸 위로 올려주세요

2024-07-14 19:59 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyStoreRoute.kt
> +                val store = storeItems[index]
```suggestion
            items(storeItems) { store ->
```
이렇게 해도 될거에요

2024-07-14 19:59 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
> +    chips: List<String>,
PersistentList로 수정해주세요

2024-07-14 19:59 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
> +                    JogboHashtagChip(chiptext = chips[index])
```suggestion
                items(chips) { chip ->
                    JogboHashtagChip(chiptext = chip)
```
items에 list를 넣어줄 수 있어요

2024-07-14 19:59 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/MyStoreRoute.kt
> +                store.isLiked?.let {
단순한 true/false의 경우 let말고 if문을 쓰는게 더 메모리적으로 좋습니다 :)

2024-07-15 09:42 UTC, chattymin approved these changes
진짜 진짜 고생했습니다!!!
남은부분도 화이팅~~~~!!!

2024-07-15 09:50 UTC, merged