[Feature/#62] my new jogbo
Team-Hankki/hankki-android pull request #76
Opened 2024-07-16 18:17 UTC by hyeeum

- closed #62

## *⛳️ Work Description*
- 텍스트필드 커스텀
- 네비게이터 연결

## *📸 Screenshot*

https://github.com/user-attachments/assets/458f4385-98f8-4197-ae9c-13dacfaabe86

## *📢 To Reviewers*
- HankkiCountTextField 해석하기 어려울 것 같아서(저는 어려웠음) 주석도 같이 달아서 PR올릴게요! 병합할때 지우고 병합하겠습니당
- 텍스트필드....어렵다 어려워...
- 피그마 컴포넌트 프레임에 있어서 core에 넣긴했는데 my모듈로 변경할까요? 약간 의문...
- 나도 서버 통신 하고 싶어요ㅠ

2024-07-16 18:59 UTC, chattymin requested changes
어려운 기능이었는데 고생하셨습니다 :)

2024-07-16 18:59 UTC, chattymin commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiCountTextField.kt
> +    var textFieldValue by remember { mutableStateOf(TextFieldValue(text = value)) }
value는 state로 hoisting 해주세요~

2024-07-16 18:59 UTC, chattymin commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiCountTextField.kt
> +    tailingIcon: Boolean,
```suggestion
    trailingIcon: Boolean,
```
오타 수정해주세용 ㅎㅎ

2024-07-16 18:59 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
> +    modifier: Modifier = Modifier,
옵셔널이랑 필수랑 위치 맞춰주세요

2024-07-16 19:14 UTC, hyeeum commented on feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
> +    modifier: Modifier = Modifier,
순서가 왜...왜이렇게 됐을까요 얼른 고쳐서 올리겠습니다 !

2024-07-16 19:38 UTC, hyeeum commented on core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiCountTextField.kt
> +    tailingIcon: Boolean,
맨끝에 오는 컴포넌트라 tail인줄...감사합니닷!

2024-07-16 20:40 UTC, chattymin approved these changes
굿굿!!
state hoisting은 앱잼 끝나고 수정해주세요 :)

2024-07-17 06:18 UTC, 0se0 approved these changes
고생하셨습니다.

2024-07-17 07:01 UTC, merged