[Feature/#91] my page dialog
Team-Hankki/hankki-android pull request #93
Opened 2024-07-17 22:48 UTC by hyeeum

- closed #91

## *⛳️ Work Description*
- core 컴포넌트에 있는 다이얼로그로 교체했습니다
- 다이얼로그를 route에서 상태를 주지 않고 viewmodel을 통해 관리합니다.

## *📸 Screenshot*

이전화면과 동일하여 촬영X

## *📢 To Reviewers*
- enum 신기하당

2024-07-17 22:57 UTC, chattymin requested changes
고생하셨습니다!!
수정화이팅입니다 ㅎㅎ

2024-07-17 22:57 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
> +            onPositiveButtonClicked = { updateDialogState() })
```suggestion
            onNegativeButtonClicked = updateDialogState,
            onPositiveButtonClicked = updateDialogState
        )
```
이렇게 해도 될껄요~~

2024-07-17 22:57 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboViewModel.kt
> +    }
왜 입력값의 반대로 동작하는걸까요??
`updateDialog(false)`라는 함수를 호출 했을 때 dialog가 꺼지는 것을 예상할 것 같습니다.

2024-07-17 22:57 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
> +            onConfirmation = { updateShareDialogState() }
```suggestion
            onConfirmation = updateShareDialogState
```
원래 이랬는데 왜 수정한건가용??

2024-07-17 22:57 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
> +    showWebView: MutableState<String>,
이건 다음 PR에서 SharedFlow로 수정하신다고 하셨죠!!
화이팅입니다 :)

2024-07-17 22:57 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
> +        if (type == FAQ) Uri.parse("https://fast-kilometer-dbf.notion.site/FAQ-bb4d74b681d14f4f91bbbcc829f6d023?pvs=4") else Uri.parse(
링크는 상수로 빼줍시다~~~~

2024-07-17 22:57 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/mypage/MyState.kt
> +    val showWebView: MutableState<String> = mutableStateOf("")
State내부에 mutableState를 가지고 있으면 안됩니다아!!
SharedFlow로 바꾸는 과정에서 이것도 수정해주세요 :)

2024-07-17 23:13 UTC, hyeeum commented on feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
> +            onConfirmation = { updateShareDialogState() }
그러게요...제가 왜 이랬을까요..............................

2024-07-18 03:00 UTC, 0se0 approved these changes
수고하셨습니다.

2024-07-18 08:54 UTC, chattymin approved these changes
굿!!! 고생하셨습니다 :)

2024-07-18 08:54 UTC, chattymin commented on feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
> +            myJogboViewModel.updateJogboSeleted(
놀랍게도 이것도 리플렉션이 된답니답!!

2024-07-18 08:57 UTC, hyeeum commented on feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
> +            myJogboViewModel.updateJogboSeleted(
세상에 얼른 수정하겠습니다

2024-07-18 09:11 UTC, merged